<a href="https://colab.research.google.com/github/syedadilejazz/DBSCAN-Algorithm/blob/master/Text_Representation_Word_Embeddings_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Some common terms to remember:

Corpus-Entire Text
Vocabulary-Unique words in Corpus
Document-One row/One line
Word-single word

BoW → TF-IDF → Word2Vec → FastText → BERT Embeddings

Bag of words(Sklearn CountVectorizer)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df['text'])
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [ ]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}

In [ ]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [ ]:
print(df["text"][0])
print(bow[0].toarray())

people watch dswithbappy
[[0 1 1 1 0]]

In [ ]:
print(df["text"][1])
print(bow[1].toarray())

dswithbappy watch dswithbappy
[[0 2 0 1 0]]

In [ ]:
print(df["text"][2])
print(bow[2].toarray())

people write comment
[[1 0 1 0 1]]

In [ ]:
print(df["text"][3])
print(bow[3].toarray())

dswithbappy write comment
[[1 1 0 0 1]]

In [ ]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [ ]:
# new
cv.transform(['Bappy watch dswithbappy,Adil watch consistency hello']).toarray()

array([[0, 1, 0, 2, 0]])

In [ ]:
# new
cv.transform(["I love AI"]).toarray()

array([[0, 0, 0, 0, 0]])

N-grams

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}

In [ ]:
print(df["text"][0])
print(bow[0].toarray())

people watch dswithbappy
[[0 0 1 0 1 0]]

In [ ]:
print(df["text"][1])
print(bow[1].toarray())

dswithbappy watch dswithbappy
[[1 0 0 0 1 0]]

In [ ]:
print(df["text"][2])
print(bow[2].toarray())

people write comment
[[0 0 0 1 0 1]]

In [ ]:
print(df["text"][3])
print(bow[3].toarray())

dswithbappy write comment
[[0 1 0 0 0 1]]

In [ ]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}

In [ ]:
print(df["text"][0])
print(bow[0].toarray())
print(df["text"][1])
print(bow[1].toarray())
print(df["text"][2])
print(bow[2].toarray())
print(df["text"][3])
print(bow[3].toarray())

people watch dswithbappy
[[0 0 1 0]]
dswithbappy watch dswithbappy
[[1 0 0 0]]
people write comment
[[0 0 0 1]]
dswithbappy write comment
[[0 1 0 0]]

TF-IDF (Term frequency- Inverse document frequency)

Frequent in document
BUT
Rare across documents
=
Important word

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [ ]:
arr = tfid.fit_transform(df['text']).toarray()
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [ ]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]

Cosine Similarity

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute cosine similarity
similarity = cosine_similarity(arr)

print(similarity)

[[1.         0.74515867 0.35430066 0.24682625]
 [0.74515867 1.         0.         0.42269915]
 [0.35430066 0.         1.         0.70860132]
 [0.24682625 0.42269915 0.70860132 1.        ]]

In [ ]:
import pandas as pd

similarity_matrix = cosine_similarity(arr)
docs = ['D1', 'D2', 'D3', 'D4']

df_sim = pd.DataFrame(
    similarity_matrix,
    columns=docs,
    index=docs
)
print(df_sim)

          D1        D2        D3        D4
D1  1.000000  0.745159  0.354301  0.246826
D2  0.745159  1.000000  0.000000  0.422699
D3  0.354301  0.000000  1.000000  0.708601
D4  0.246826  0.422699  0.708601  1.000000

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving IMDB Dataset.csv to IMDB Dataset.csv

In [ ]:
df = pd.read_csv(r'IMDB Dataset.csv')
print("Shape",df.shape)
print("Columns",df.columns)
df.head(3)

Shape (50000, 2)
Columns Index(['review', 'sentiment'], dtype='object')

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [ ]:
import time
start = time.time()
arr = tfid.fit_transform(df['review'][0:10000]).toarray()
arr
print(time.time()-start)

5.404764175415039

Word2Vec

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 17.5 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
import numpy as np
import pandas as pd
import gensim
import os

In [ ]:
!pip install --upgrade gensim --user

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)

In [42]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [43]:
df=pd.read_csv(r"IMDB Dataset.csv")
print(df.columns)
print(df.shape)
df.head(2)

Index(['review', 'sentiment'], dtype='object')
(50000, 2)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive

In [45]:
import pandas as pd
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

# Read CSV
df = pd.read_csv("battles.csv")

# Check columns
print(df.columns)

# Create empty list
story = []

# Suppose text column is named 'name'
# Replace 'name' with your actual text column

for text in df['name'].dropna():

    # Sentence tokenization
    raw_sent = sent_tokenize(str(text))

    # Word tokenization + preprocessing
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

# View output
print(story[:5])

Index(['name', 'year', 'battle_number', 'attacker_king', 'defender_king',
       'attacker_1', 'attacker_2', 'attacker_3', 'attacker_4', 'defender_1',
       'defender_2', 'defender_3', 'defender_4', 'attacker_outcome',
       'battle_type', 'major_death', 'major_capture', 'attacker_size',
       'defender_size', 'attacker_commander', 'defender_commander', 'summer',
       'location', 'region', 'note'],
      dtype='object')
[['battle', 'of', 'the', 'golden', 'tooth'], ['battle', 'at', 'the', 'mummer', 'ford'], ['battle', 'of', 'riverrun'], ['battle', 'of', 'the', 'green', 'fork'], ['battle', 'of', 'the', 'whispering', 'wood']]

In [46]:
story[0]

['battle', 'of', 'the', 'golden', 'tooth']

In [47]:
model = gensim.models.Word2Vec(
    window=10,#Look 10 words left and 10 words right
    min_count=2#Ignore rare words appearing less than 2 times.
)

In [49]:
#Word2Vec scans all words,and builds:unique word list,frequency count,indexing
x=model.build_vocab(story)
x

WARNING:gensim.models.keyedvectors:sorting after vectors have been allocated is expensive & error-prone

In [50]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(65, 740)

In [51]:
model.wv.most_similar('battle')

[('end', 0.21907076239585876),
 ('deepwood', 0.2161720097064972),
 ('square', 0.09309576451778412),
 ('moat', 0.09291721135377884),
 ('torrhen', 0.07979955524206161),
 ('motte', 0.06284984201192856),
 ('storm', 0.05433368682861328),
 ('cailin', 0.027057606726884842),
 ('darry', 0.016134917736053467),
 ('of', -0.010514998808503151)]

In [52]:
model.wv.similarity('battle','cailin')

np.float32(0.0270576)

In [53]:
vec = model.wv.get_normed_vectors()

In [54]:
vec

array([[-0.14847298,  0.06313413,  0.08962155, ..., -0.04127668,
        -0.16401833,  0.07770426],
       [-0.00948406,  0.00418162,  0.09025731, ..., -0.12453795,
         0.01594284,  0.11305824],
       [ 0.00166332,  0.05412817, -0.11983024, ...,  0.00901615,
         0.1444631 , -0.12346061],
       ...,
       [ 0.14659119, -0.08034728, -0.01925806, ..., -0.10340908,
        -0.02991442,  0.10043302],
       [-0.12351408,  0.02150638, -0.12416432, ...,  0.08335102,
         0.01362773,  0.05213169],
       [-0.14210768,  0.16032529, -0.00340777, ..., -0.12839994,
        -0.0432059 , -0.09568229]], dtype=float32)

In [55]:
model.wv.get_normed_vectors().shape

(19, 100)

In [56]:
y = model.wv.index_to_key

In [57]:
len(y)

19

In [58]:
y

['of',
 'battle',
 'the',
 'siege',
 'sack',
 'winterfell',
 'retaking',
 'harrenhal',
 'end',
 'storm',
 'square',
 'torrhen',
 'motte',
 'deepwood',
 'cailin',
 'moat',
 'darry',
 'riverrun',
 'ford']

In [59]:
from sklearn.decomposition import PCA

In [60]:
pca = PCA(n_components=3)

In [61]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [62]:
X

array([[ 0.28082457,  0.19663002, -0.12184384],
       [-0.5422003 ,  0.12410947,  0.12193242],
       [-0.05998543, -0.56907994, -0.29233602],
       [ 0.32070482,  0.48961112,  0.30062526],
       [ 0.19626959, -0.3383861 , -0.16044322],
       [ 0.3404975 ,  0.3771467 , -0.3537204 ],
       [ 0.06091859,  0.07011642, -0.14675836],
       [ 0.49283153,  0.14807734,  0.24687372],
       [-0.47656938,  0.37563148, -0.29290432],
       [-0.29141843,  0.03020425, -0.02120627],
       [-0.06476451,  0.03382521,  0.06552149],
       [ 0.04707325, -0.4294897 ,  0.21520746],
       [-0.11377023, -0.02392145,  0.56203306],
       [-0.52026075, -0.01315067,  0.20549355],
       [ 0.00103048, -0.5237664 ,  0.11977651],
       [-0.12645106,  0.2794754 ,  0.20522296],
       [-0.16428998, -0.04856743, -0.16985267],
       [ 0.10718337, -0.00411908, -0.7169417 ],
       [ 0.5123764 , -0.17434639,  0.23332065]], dtype=float32)

In [63]:
X.shape

(19, 3)

In [64]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()