<a href="https://colab.research.google.com/github/syedadilejazz/DBSCAN-Algorithm/blob/master/Text_Representation_Word_Embeddings_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Some common terms to remember:

Corpus-Entire Text
Vocabulary-Unique words in Corpus
Document-One row/One line
Word-single word

BoW → TF-IDF → Word2Vec → FastText → BERT Embeddings

Bag of words(Sklearn CountVectorizer)

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [6]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}

In [7]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [8]:
print(df["text"][0])
print(bow[0].toarray())

people watch dswithbappy
[[0 1 1 1 0]]

In [9]:
print(df["text"][1])
print(bow[1].toarray())

dswithbappy watch dswithbappy
[[0 2 0 1 0]]

In [10]:
print(df["text"][2])
print(bow[2].toarray())

people write comment
[[1 0 1 0 1]]

In [11]:
print(df["text"][3])
print(bow[3].toarray())

dswithbappy write comment
[[1 1 0 0 1]]

In [12]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [13]:
# new
cv.transform(['Bappy watch dswithbappy,Adil watch consistency hello']).toarray()

array([[0, 1, 0, 2, 0]])

In [14]:
# new
cv.transform(["I love AI"]).toarray()

array([[0, 0, 0, 0, 0]])

N-grams

In [15]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [16]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [17]:
bow = cv.fit_transform(df['text'])

In [18]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}

In [19]:
print(df["text"][0])
print(bow[0].toarray())

people watch dswithbappy
[[0 0 1 0 1 0]]

In [20]:
print(df["text"][1])
print(bow[1].toarray())

dswithbappy watch dswithbappy
[[1 0 0 0 1 0]]

In [21]:
print(df["text"][2])
print(bow[2].toarray())

people write comment
[[0 0 0 1 0 1]]

In [22]:
print(df["text"][3])
print(bow[3].toarray())

dswithbappy write comment
[[0 1 0 0 0 1]]

In [23]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [24]:
bow = cv.fit_transform(df['text'])

In [25]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}

In [26]:
print(df["text"][0])
print(bow[0].toarray())
print(df["text"][1])
print(bow[1].toarray())
print(df["text"][2])
print(bow[2].toarray())
print(df["text"][3])
print(bow[3].toarray())

people watch dswithbappy
[[0 0 1 0]]
dswithbappy watch dswithbappy
[[1 0 0 0]]
people write comment
[[0 0 0 1]]
dswithbappy write comment
[[0 1 0 0]]

TF-IDF (Term frequency- Inverse document frequency)

Frequent in document
BUT
Rare across documents
=
Important word

In [27]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [29]:
arr = tfid.fit_transform(df['text']).toarray()
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [30]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]

Cosine Similarity

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

# Compute cosine similarity
similarity = cosine_similarity(arr)

print(similarity)

[[1.         0.74515867 0.35430066 0.24682625]
 [0.74515867 1.         0.         0.42269915]
 [0.35430066 0.         1.         0.70860132]
 [0.24682625 0.42269915 0.70860132 1.        ]]

In [32]:
import pandas as pd

similarity_matrix = cosine_similarity(arr)
docs = ['D1', 'D2', 'D3', 'D4']

df_sim = pd.DataFrame(
    similarity_matrix,
    columns=docs,
    index=docs
)
print(df_sim)

          D1        D2        D3        D4
D1  1.000000  0.745159  0.354301  0.246826
D2  0.745159  1.000000  0.000000  0.422699
D3  0.354301  0.000000  1.000000  0.708601
D4  0.246826  0.422699  0.708601  1.000000

In [39]:
from google.colab import files

uploaded = files.upload()

Saving IMDB Dataset.csv to IMDB Dataset.csv

In [40]:
df = pd.read_csv(r'IMDB Dataset.csv')
print("Shape",df.shape)
print("Columns",df.columns)
df.head(3)

Shape (50000, 2)
Columns Index(['review', 'sentiment'], dtype='object')

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [42]:
import time
start = time.time()
arr = tfid.fit_transform(df['review'][0:10000]).toarray()
arr
print(time.time()-start)

5.37481164932251

Word2Vec

In [43]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 57.4 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [44]:
import numpy as np
import pandas as pd
import gensim
import os

In [45]:
!pip install --upgrade gensim --user

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)

In [46]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [48]:
df=pd.read_csv(r"battles.csv")
print(df.columns)
print(df.shape)
df.head(2)

Index(['name', 'year', 'battle_number', 'attacker_king', 'defender_king',
       'attacker_1', 'attacker_2', 'attacker_3', 'attacker_4', 'defender_1',
       'defender_2', 'defender_3', 'defender_4', 'attacker_outcome',
       'battle_type', 'major_death', 'major_capture', 'attacker_size',
       'defender_size', 'attacker_commander', 'defender_commander', 'summer',
       'location', 'region', 'note'],
      dtype='object')
(38, 25)

,name,year,battle_number,attacker_king,defender_king,attacker_1,attacker_2,attacker_3,attacker_4,defender_1,...,major_death,major_capture,attacker_size,defender_size,attacker_commander,defender_commander,summer,location,region,note
0,Battle of the Golden Tooth,298,1,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Tully,...,1.0,0.0,15000.0,4000.0,Jaime Lannister,"Clement Piper, Vance",1.0,Golden Tooth,The Westerlands,NaN
1,Battle at the Mummer's Ford,298,2,Joffrey/Tommen Baratheon,Robb Stark,Lannister,NaN,NaN,NaN,Baratheon,...,1.0,0.0,NaN,120.0,Gregor Clegane,Beric Dondarrion,1.0,Mummer's Ford,The Riverlands,NaN

In [50]:
import pandas as pd
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

# Read CSV
df = pd.read_csv("battles.csv")

# Check columns
print(df.columns)

# Create empty list
story = []

# Suppose text column is named 'name'
# Replace 'name' with your actual text column

for text in df['name'].dropna():

    # Sentence tokenization
    raw_sent = sent_tokenize(str(text))

    # Word tokenization + preprocessing
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

# View output
print(story[:5])

Index(['name', 'year', 'battle_number', 'attacker_king', 'defender_king',
       'attacker_1', 'attacker_2', 'attacker_3', 'attacker_4', 'defender_1',
       'defender_2', 'defender_3', 'defender_4', 'attacker_outcome',
       'battle_type', 'major_death', 'major_capture', 'attacker_size',
       'defender_size', 'attacker_commander', 'defender_commander', 'summer',
       'location', 'region', 'note'],
      dtype='object')
[['battle', 'of', 'the', 'golden', 'tooth'], ['battle', 'at', 'the', 'mummer', 'ford'], ['battle', 'of', 'riverrun'], ['battle', 'of', 'the', 'green', 'fork'], ['battle', 'of', 'the', 'whispering', 'wood']]

In [51]:
story[0]

['battle', 'of', 'the', 'golden', 'tooth']

In [52]:
model = gensim.models.Word2Vec(
    window=10,#Look 10 words left and 10 words right
    min_count=2#Ignore rare words appearing less than 2 times.
)

In [72]:
#Word2Vec scans all words,and builds:unique word list,frequency count,indexing
x=model.build_vocab(story)
x

WARNING:gensim.models.keyedvectors:sorting after vectors have been allocated is expensive & error-prone

In [54]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(65, 740)

In [56]:
model.wv.most_similar('battle')

[('cailin', 0.16072511672973633),
 ('ford', 0.15923358500003815),
 ('deepwood', 0.1372530609369278),
 ('moat', 0.12300871312618256),
 ('riverrun', 0.08549514412879944),
 ('siege', 0.06820005923509598),
 ('end', 0.033856913447380066),
 ('darry', 0.022314654663205147),
 ('winterfell', 0.009522010572254658),
 ('torrhen', 0.008448505774140358)]

In [58]:
model.wv.similarity('battle','cailin')

np.float32(0.16072512)

In [60]:
vec = model.wv.get_normed_vectors()

In [61]:
vec

array([[-0.00941404,  0.00428275,  0.09036892, ..., -0.1245184 ,
         0.01592483,  0.11300997],
       [-0.14864816,  0.06321564,  0.08949912, ..., -0.04124121,
        -0.1640023 ,  0.077705  ],
       [ 0.00166332,  0.05412817, -0.11983024, ...,  0.00901615,
         0.1444631 , -0.12346061],
       ...,
       [ 0.02121599, -0.15998559,  0.07486263, ..., -0.04222368,
        -0.12658063,  0.06841443],
       [ 0.02979783,  0.1167038 ,  0.04876131, ..., -0.03081958,
         0.05982181, -0.11656434],
       [ 0.16395864, -0.16471368, -0.10945941, ..., -0.04549181,
         0.06441382,  0.00568599]], dtype=float32)

In [62]:
model.wv.get_normed_vectors().shape

(19, 100)

In [63]:
y = model.wv.index_to_key

In [64]:
len(y)

19

In [65]:
y

['of',
 'battle',
 'the',
 'siege',
 'sack',
 'winterfell',
 'retaking',
 'harrenhal',
 'end',
 'storm',
 'square',
 'torrhen',
 'motte',
 'deepwood',
 'cailin',
 'moat',
 'darry',
 'riverrun',
 'ford']

In [66]:
from sklearn.decomposition import PCA

In [67]:
pca = PCA(n_components=3)

In [68]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [69]:
X

array([[-0.5422242 ,  0.12198914,  0.12357287],
       [ 0.2814807 ,  0.19796786, -0.12022569],
       [-0.05999105, -0.56621724, -0.2981774 ],
       [ 0.5127376 , -0.17644827,  0.23149465],
       [ 0.10698911,  0.00323264, -0.7170299 ],
       [ 0.19726445, -0.33631197, -0.16380079],
       [-0.16524062, -0.04659017, -0.16951041],
       [-0.1270538 ,  0.27685547,  0.20825157],
       [ 0.00104137, -0.5242385 ,  0.11456364],
       [-0.51992303, -0.01510605,  0.205311  ],
       [-0.11379746, -0.02949191,  0.56172496],
       [ 0.04754397, -0.43232313,  0.21069627],
       [-0.06512176,  0.03309112,  0.06564366],
       [ 0.3401595 ,  0.3812162 , -0.3500097 ],
       [ 0.32042575,  0.48687676,  0.30570132],
       [-0.29072693,  0.03033822, -0.02114551],
       [-0.47662532,  0.37857378, -0.28914735],
       [ 0.49303153,  0.14553736,  0.24840057],
       [ 0.06003012,  0.07104915, -0.14631347]], dtype=float32)

In [70]:
X.shape

(19, 3)

In [71]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()